### ISSUE TITLE
Shape of Mask and Shape of Image

### ISSUE THREAD

**Issue by cseuring** [lcls-psana/psocake#15]
I want to do hitfinding and therefore create a mask.

I get this error message when running the mask module.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/psocake/MaskPanel.py", line 754, in deployMask
  File "build/bdist.linux-x86_64/egg/psocake/MaskPanel.py", line 682, in getCombinedStaticMask
ValueError: operands could not be broadcast together with shapes (1738,1742) (32,185,388) (1738,1742) 

Is this a problem for the saved masks? The saved masks have a dimension of either .h5 format (32,185,388) or in .npy format (1480,1552), there is no assembled mask (1738,1742).

**Comment by chuckie82** [comment]
(1738,1742) seems way to big for a cspad. 
Can you point me to the experiment name/run number and are you making a custom mask? I will try to reproduce it in the morning.

**Comment by chuckie82** [comment]
I get the following mask shapes which looks correct. Could you describe the steps you are using to create this mask?

mask.npy
(32, 185, 388)

staticMask.h5
<HDF5 dataset "mask": shape (1480, 1552), type "<i8">
