### ISSUE TITLE
feature request - load .data files

### ISSUE THREAD

**Issue by fredericpoitevin** [lcls-psana/psocake#26]
Bhavna was asking if we could load .data files directly, instead of having to convert them to .npy or .npz first.

**Comment by fredericpoitevin** [comment]
(I'd like to assign this to me but it does not seem to be possible; any way: I'll take care of that)

**Comment by chuckie82** [comment]
could you remind me why we need to convert .data to .npy?

**Comment by fredericpoitevin** [comment]
For example, if one is interested in using the "Load image" button to load the files in calib:
![image](https://user-images.githubusercontent.com/4610338/104657987-cc617200-5676-11eb-9ab0-d373e0bddf68.png)

**Comment by chuckie82** [comment]
calibman can display .data files

pixel_rms can be displayed by selecting it via "Experiment Parameters Panel -> Display -> Image Properties"
(non-autoranging detectors only)

**Comment by fredericpoitevin** [comment]
I have some issues running calibman at the moment (maybe because I don't know how to use it yet):
```(ana-4.0.9) [fpoitevi@psanagpu104 ~]$ calibman -e cxilv4418 -d jungfrau4M -r 109
Start Calibration Manager GUI
Optional parameters 
  instr_name : cxi 
  exp_name   : cxilv4418 
  calib_dir  : /reg/d/psdm/cxi/cxilv4418/calib 
  run_number : 0109 
  detectors  : jungfrau4M
Traceback (most recent call last):
  File "/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.9/bin/calibman", line 100, in <module>
    StartCalibManager()
  File "/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.9/bin/calibman", line 86, in __init__
    gui = GUIMain(None, app, **dict_opts)
  File "/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.9/lib/python2.7/site-packages/CalibManager/GUIMain.py", line 63, in __init__
    self.guitabs   = GUIMainTabs(self) # QtWidgets.QTextEdit()
  File "/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.9/lib/python2.7/site-packages/CalibManager/GUIMainTabs.py", line 75, in __init__
    self.guiSelector()
  File "/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.9/lib/python2.7/site-packages/CalibManager/GUIMainTabs.py", line 151, in guiSelector
    self.gui_win = GUIDark(self)
  File "/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.9/lib/python2.7/site-packages/CalibManager/GUIDark.py", line 39, in __init__
    self.guidarklist = GUIDarkList(self)
  File "/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.9/lib/python2.7/site-packages/CalibManager/GUIDarkList.py", line 68, in __init__
    self.updateList()
  File "/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.9/lib/python2.7/site-packages/CalibManager/GUIDarkList.py", line 178, in updateList
    item, widg = self.create_or_use_guidarklistitem(run_num)
  File "/cds/sw/ds/ana/conda1/inst/envs/ana-4.0.9/lib/python2.7/site-packages/CalibManager/GUIDarkList.py", line 207, in create_or_use_guidarklistitem
    item.setTextColor(QtGui.QColor(0, 0, 0, alpha=0)) # set item text invisible. All pars in the range [0,255]
AttributeError: 'QListWidgetItem' object has no attribute 'setTextColor'```

and I believe Bhavna is interested in autoranging detectors.

It should not be too hard to load .data:
![image](https://user-images.githubusercontent.com/4610338/104664695-c07cac80-5684-11eb-8617-601034605d05.png)

I can't launch psocake at the moment for some reason, but I'll make sure I can display this image and make a PR.
